In [37]:
import altair as alt
import pandas as pd
from data.rent_produtos_mitra import buscar_produtos

In [38]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [39]:
produtos_df = buscar_produtos()

In [40]:
produtos_df.head()

,COD_REL_APURACAO_FORM,DATA_COTACAO,TESOURARIA,GRUPO,CARTEIRA,PRODUTO,POSICAO_DF
0,76198,2025-11-10,[CERES TOTAL],Estruturado,Emater MG Básico_BD (009149),CHAPADA DIAMANTINA CIC DE FI MULT - RESP LIMIT...,1818207.43
1,76198,2025-11-10,[CERES TOTAL],Estruturado,Emater MG FlexCeres_CV (009151),CHAPADA DOS GUIMARÃES CLASSE ÚNICA DE INVESTIM...,4573114.64
2,76198,2025-11-10,[CERES TOTAL],Estruturado,Emater MG FlexCeres_CV (009151),CHAPADA DIAMANTINA CIC DE FI MULT - RESP LIMIT...,4764513.45
3,76198,2025-11-10,[CERES TOTAL],Estruturado,Emater MG Saldado_BD (009150),CHAPADA DIAMANTINA CIC DE FI MULT - RESP LIMIT...,2832744.03
4,76198,2025-11-10,[CERES TOTAL],Estruturado,Emater MG Saldado_BD (009150),CHAPADA DOS GUIMARÃES CLASSE ÚNICA DE INVESTIM...,2718947.77

In [41]:
rel_embrapa = produtos_df[(produtos_df['DATA_COTACAO'] == '2026-07-23') & (produtos_df['TESOURARIA'] == 'Embrapa Básico_BD')]
rel_embrapa['COD_REL_APURACAO_FORM'].unique()

array([83996, 83419, 82960])

In [43]:
rel_embrapa_83419 = produtos_df[(produtos_df['DATA_COTACAO'] == '2026-07-23') & (produtos_df['TESOURARIA'] == 'Embrapa Básico_BD') & (produtos_df['COD_REL_APURACAO_FORM'] == 83419)]
rel_embrapa_83996 = produtos_df[(produtos_df['DATA_COTACAO'] == '2026-07-23') & (produtos_df['TESOURARIA'] == 'Embrapa Básico_BD') & (produtos_df['COD_REL_APURACAO_FORM'] == 83996)]

In [44]:
compara_embrapa = rel_embrapa_83996.merge(rel_embrapa_83419, how='inner', on='PRODUTO', suffixes=('_83996', '_83419'))[['PRODUTO', 'POSICAO_DF_83996', 'POSICAO_DF_83419']]
compara_embrapa['DIFERENCA'] = compara_embrapa['POSICAO_DF_83996'] - compara_embrapa['POSICAO_DF_83419']
compara_embrapa

,PRODUTO,POSICAO_DF_83996,POSICAO_DF_83419,DIFERENCA
0,CORPORATE FINANCIAL CENTER (304),5516594.70,5516594.70,0.00
1,Embrapa Básico_BD_Emprestimos,1468.93,1468.93,0.00
2,Embrapa Básico_BD_Emprestimos,98435365.71,1468.93,98433896.78
3,Embrapa Básico_BD_Emprestimos,1468.93,98435365.71,-98433896.78
4,Embrapa Básico_BD_Emprestimos,98435365.71,98435365.71,0.00
5,Embrapa Básico_BD_Financiamentos,25731.11,25731.11,0.00
6,SAFRA CAPITAL MARKET PREMIUM CIC RF REFERENCIA...,124147748.83,124147748.83,0.00
7,NTNB_15/05/2035_760199,605197177.13,605197177.13,0.00
8,ITAÚ INSTITUCIONAL RF REF DI FIF RES LIMITADA ...,124469884.84,124469884.84,0.00
9,NTNB_15/05/2055_760199,367389013.20,367389013.20,0.00
10,NTNB_15/08/2028_760199,23226575.54,23226575.54,0.00
11,BB PREVIDENCIÁRIO RENDA FIXA REFERENCIADO DI L...,165061920.30,165061920.30,0.00
12,NTNB_15/05/2037_760199,20852786.88,20852786.88,0.00
13,NTNB_15/08/2032_760199,363860704.20,363860704.20,0.00
14,NTNB_15/05/2033_760199,203739066.94,203739066.94,0.00
15,BRADESCO CLASSE DE INVESTIMENTO RF REFERENCIAD...,122843059.00,122843059.00,0.00
16,NTNB_15/08/2040_760199,575594242.76,575594242.76,0.00
17,NTNB_15/08/2030_760199,199704585.26,199704585.26,0.00
18,NTNC_01/01/2031_770100,294743569.24,294743569.24,0.00
19,NTNB_15/08/2026_760199,146123280.49,146123280.49,0.00
20,NTNB_15/05/2045_760199,1163371392.17,1163371392.17,0.00
21,NTNB_15/08/2060_760199,151128099.43,151128099.43,0.00
22,CLASSE ÚNICA DE COTAS DO EROS FUNDO DE INVESTI...,684155776.21,684155776.21,0.00
23,NTNB_15/08/2050_760199,808380352.88,808380352.88,0.00
24,4UM SMALL CAPS FIF - CLASSE DE INVESTIMENTO EM...,29755877.23,29755877.23,0.00
25,CLASSE ÚNICA DE COTAS DO TRÍGONO FLAGSHIP 60 S...,6376442.63,6376442.63,0.00
26,SANTANDER DIVIDENDOS AÇÕES - CIC FIF RESP LIMI...,27590810.73,27590810.73,0.00
27,OCEANA SERRA DA CAPIVARA CLASSE DE FIF AÇÕES -...,107738727.07,107738727.07,0.00
28,CHAPADA DOS VEADEIROS CLASSE DE FIF AÇÕES - RE...,72663519.28,72663519.28,0.00
29,CLASSE ÚNICA DE COTAS DO GUEPARDO INSTITUCIOAL...,26120549.15,26120549.15,0.00
30,FCAP3*,47101.40,47101.40,0.00
31,TIJUCA CLASSE DE FIF AÇÕES - RESP LIMITADA - C...,142180346.00,142180346.00,0.00
32,CHAPADA DOS GUIMARÃES CLASSE ÚNICA DE INVESTIM...,82445461.98,82445461.98,0.00
33,CHAPADA DIAMANTINA CIC DE FI MULT - RESP LIMIT...,111216912.94,111216912.94,0.00
34,RB CAPITAL DESENV RESIDENCIAL II FII,18993.84,18993.84,0.00
35,SHOPPING CONJUNTO NACIONAL,108818782.56,108818782.56,0.00
36,EDIFICIO CERES,18721250.51,18721250.51,0.00
37,CORPORATE FINANCIAL CENTER (303),4100521.07,4100521.07,0.00
38,CENESP (BLOCO J),643421.86,643421.86,0.00
39,CENESP (BLOCO C),7783078.89,7783078.89,0.00
40,SHOPPING RECIFE,93918516.20,93918516.20,0.00

In [31]:
compara_embrapa.PRODUTO[compara_embrapa.PRODUTO.duplicated()]

11    Embrapa Básico_BD_Emprestimos
13    Embrapa Básico_BD_Emprestimos
14    Embrapa Básico_BD_Emprestimos
Name: PRODUTO, dtype: str